title: Stackbit Book Theme
baseURL: /
params:
  layout_type: full-width
  style: bold
  palette: gray
  mode: light
  base_font: sans-serif
  header:
    title: Kaizen 101 for Developers
    logo: images/adorable-pine.png
    logo_alt: Kaizen 101 for Developers Logo
    has_primary_nav: true
    primary_nav_links:
      - label: Pricing
        url: 'https://leanpub.com/kaizen101fordevelopers'
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: Want a Discount? Use this Button.
        url: 'https://leanpub.com/kaizen101fordevelopers'
        style: primary
    has_anncmnt: true
    anncmnt_content: >
      Kaizen 101 for Developers is published on LeanPub, helping authors do
      more. [**Learn about it.**](https://leanpub.com/authors)
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    logo_alt: Marketing Playbook logo
    has_primary_nav: false
    primary_nav_title: Company
    primary_nav_links:
      - label: Story
        url: /story
        style: link
      - label: Pricing
        url: /pricing
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: false
    secondary_nav_title: Legal
    secondary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_tertiary_nav: false
    has_social: true
    social_links:
      - label: LinkedIn
        url: 'https://www.youtube.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - label: Github
        url: 'https://vimeo.com/'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: Facebook
        url: 'https://www.facebook.com/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
    content: >-
      &copy; Virtually(Creative). All rights reserved. This Jamstack site was
      created with <a
      href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=book&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a><br/><div>Icons made by <a
      href="https://www.freepik.com" title="Freepik">Freepik</a> from <a
      href="https://www.flaticon.com/"
      title="Flaticon">www.flaticon.com</a></div>
  domain: 'https://kaizen101.dev'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
